In [21]:
import numpy as np

In [22]:
# 1차원 배열 생성

In [23]:
## arange()

In [24]:
arr = np.arange(12)

In [25]:
print(arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [26]:
print(arr.ndim)
print(arr.shape)

1
(12,)


In [27]:
print(type(arr))

<class 'numpy.ndarray'>


In [28]:
## array()

In [29]:
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [30]:
print(arr)
print(arr.ndim)
print(arr.shape)
print(type(arr))

[ 0  1  2  3  4  5  6  7  8  9 10 11]
1
(12,)
<class 'numpy.ndarray'>


In [31]:
# 2차원 배열 생성

In [32]:
b = np.array([[1, 2, 3], [4, 5, 6]])

In [33]:
print(b.shape)

(2, 3)


In [34]:
print(b[0, 0], b[0, 1], b[1, 0])

1 2 4


In [35]:
## zeros()

In [36]:
a = np.zeros((2, 2))

In [37]:
print(a)

[[0. 0.]
 [0. 0.]]


In [38]:
## ones()

In [39]:
b = np.ones((1, 2))

In [40]:
print(b)

[[1. 1.]]


In [41]:
## full()

In [42]:
c = np.full((2, 2), 7)

In [43]:
print(c)

[[7 7]
 [7 7]]


In [46]:
## eye() : identity 행렬 생성

In [47]:
d = np.eye(2)

In [48]:
print(d)

[[1. 0.]
 [0. 1.]]


In [49]:
d = np.eye(3)

In [50]:
print(d)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [51]:
## random.random() : 행렬 값들을 난수로 초기화

In [52]:
e = np.random.random((2, 2))

In [53]:
print(e)

[[0.3864256  0.41572917]
 [0.13393137 0.13976851]]


In [88]:
# 배열 모양 바꾸기

In [89]:
## reshape()

In [90]:
### - 1차원 배열을 2차원 배열로 모양 바꾸기

In [91]:
arr = arr.reshape(2, 6)

In [92]:
print(arr)
print(arr.shape)
print(arr.ndim)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]]
(2, 6)
2


In [93]:
### - 2차원 배열의 축 다루기 : 0 - y, 1 - x

In [94]:
print(arr.sum(axis=0))

[ 6  8 10 12 14 16]


In [95]:
print(arr.sum(axis=1))

[15 51]


In [104]:
### - 2차원 배열을 3차원 배열로 모양 바꾸기

In [105]:
arr = arr.reshape(2, 2, 3)

In [106]:
print(arr)
print(arr.shape)
print(arr.ndim)

[[[ 0  1  2]
  [ 3  4  5]]

 [[ 6  7  8]
  [ 9 10 11]]]
(2, 2, 3)
3


In [107]:
### - 3차원 배열의 축 다루기 : 0 - z, 1 - y, 2 - x

In [108]:
print(arr.sum(axis=0))

[[ 6  8 10]
 [12 14 16]]


In [109]:
print(arr.sum(axis=1))

[[ 3  5  7]
 [15 17 19]]


In [110]:
print(arr.sum(axis=2))

[[ 3 12]
 [21 30]]


In [115]:
# 축 확장 -> 차원 확장

In [116]:
x = np.array([1, 2])

In [117]:
print(x)

[1 2]


In [118]:
print(x.shape)

(2,)


In [121]:
## expand_dims()

In [122]:
y = np.expand_dims(x, axis=0)

In [123]:
print(y)
print(y.shape)

[[1 2]]
(1, 2)


In [128]:
y = np.expand_dims([1, 2], axis=1)

In [129]:
print(y)
print(y.shape)

[[1]
 [2]]
(2, 1)


In [131]:
y = np.expand_dims(y, axis=2)

In [132]:
print(y)
print(y.shape)

[[[1]]

 [[2]]]
(2, 1, 1)


In [133]:
# *** 요약 ***

In [134]:
## axis=0 : [ 안으로 들어가지 않고 외부에 [ 추가 

In [135]:
## axis=1 : [ 안으로 한번 들어가서 [ 추가

In [136]:
## axis=2 : [ 안으로 두번 들어가서 [ 추가

In [ ]:
...